local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 15.0
  publish_frequency: 1.0
  static_map: false
  inflation_radius: 0.5
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.05
  plugins:
   - {name: static_layer, type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}


  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      sensor_frame: base_link
      topic: /scan_livox_front_low_move
      data_type: LaserScan
      marking: true
      clearing: true
